name: Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v4
      - name: Check HTML and CSS with HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: true

  delivery:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest

  security_scan:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
    - name: Ensure Docker is installed
      run: docker --version

    - name: Pull Alpine/Nikto Docker image
      run: docker pull alpine/nikto

    - name: Run Nikto Scan with Volume Mount
      run: |
        docker run --rm -v $(pwd):/output alpine/nikto \
          -h http://your-target-url.com \
          -o /output/nikto_report.html

    - name: Save Nikto Report
      uses: actions/upload-artifact@v4
      with:
        name: nikto-report
        path: nikto_report.html
        
  deploy:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v4
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: /
          skip_app_build: false
