name: Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Check HTML and CSS with HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./
          css: true

  delivery:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-website:latest

  security_scan:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Run Arachni Scanner
        run: |
          docker run --rm \
            -v $(pwd)/arachni_report:/home/arachni/reports \
            arachni/arachni \
            /usr/local/arachni/bin/arachni https://orange-stone-0d1908f03.6.azurestaticapps.net/ \
            --report-save-path=/home/arachni/reports/arachni_report.afr
      - name: Convert Arachni Report to HTML
        run: |
          docker run --rm \
            -v $(pwd)/arachni_report:/home/arachni/reports \
            arachni/arachni \
            /usr/local/arachni/bin/arachni_reporter /home/arachni/reports/arachni_report.afr \
            --reporter=html:outfile=/home/arachni/reports/arachni_report.html
      - name: Upload Arachni Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: arachni-scan-report
          path: arachni_report/arachni_report.html

  deploy:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments). Is automatically present as a secret. Not to be added by the user.
          action: "upload"
          app_location: / # App source code path
          skip_app_build: true
